# Generated by Django 4.0.5 on 2022-06-05 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('proprietario', models.CharField(max_length=255)),
                ('cnpj', models.IntegerField()),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.IntegerField()),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.IntegerField()),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('via', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(max_length=255)),
                ('cpf', models.IntegerField()),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receituario.person')),
                ('crm', models.IntegerField()),
                ('especializacao', models.CharField(max_length=255)),
                ('consultorio', models.ManyToManyField(to='receituario.clinic')),
            ],
            bases=('receituario.person',),
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='receituario.person')),
                ('telefone', models.IntegerField()),
                ('endereco', models.CharField(max_length=255)),
                ('ocupacao', models.CharField(max_length=255)),
            ],
            bases=('receituario.person',),
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('exames', models.ManyToManyField(to='receituario.exam')),
                ('medicamentos', models.ManyToManyField(to='receituario.medicine')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receituario.doctor')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receituario.patient')),
            ],
            options={
                'ordering': ['paciente'],
            },
        ),
    ]
