# Generated by Django 4.0.5 on 2022-06-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receituario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
