# Generated by Django 4.0.5 on 2022-06-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receituario', '0002_prescription_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='idade',
            new_name='nascimento',
        ),
    ]
