# Generated by Django 4.0.5 on 2022-06-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receituario', '0003_rename_idade_person_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='cnpj',
            field=models.IntegerField(max_length=14),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='crm',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantidade',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telefone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.IntegerField(max_length=11),
        ),
    ]
